# -*- coding: utf-8 -*-
"""esay chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DcWE294q-qLfNQKZOYacBzCXR3-d8KR
"""

!pip install openai gradio --quiet

import os
import gradio as gr
from openai import OpenAI

os.environ["OPENAI_API_KEY"] = "Your Key "

user_state = {"step": None, "service": None}

def chatbot_logic(message, history):
    global user_state

    if len(history) == 0:
        user_state["step"] = "ask_name"
        return "أهلاً 👋، تقدر تعرفني باسمك؟"

    if user_state["step"] == "ask_name":
        user_state["step"] = "choose_service"
        return f"حياك الله {message} 🌹، معاك مساعدتك سارة.\n\nالخدمات المتاحة:\n- رفع شكوى\n- طلب موعد\n- استفسار عن نتائج\n\nاكتب اسم الخدمة اللي تبيها."

    if user_state["step"] == "choose_service":
        if "شكوى" in message:
            user_state["service"] = "complaint"
            user_state["step"] = "ask_complaint"
            return "تم اختيار خدمة رفع شكوى ✅.\n\nمن فضلك اكتب تفاصيل الشكوى."
        elif "موعد" in message:
            user_state["service"] = "appointment"
            user_state["step"] = "ask_phone"
            return "تم اختيار خدمة طلب موعد ✅.\n\nمن فضلك اكتب رقم جوالك."
        elif "استفسار" in message:
            user_state["service"] = "inquiry"
            user_state["step"] = "ask_ticket"
            return "تم اختيار خدمة الاستفسار عن النتائج ✅.\n\nمن فضلك اكتب رقم التذكرة."
        else:
            return "الرجاء اختيار خدمة صحيحة: رفع شكوى / طلب موعد / استفسار عن نتائج."

    if user_state["service"] == "complaint":
        if user_state["step"] == "ask_complaint":
            ticket = random.randint(1000, 9999)
            user_state["step"] = "done"
            return f"شكراً لك 🙏 تم رفع الشكوى بنجاح.\nرقم التذكرة: #{ticket}"

    if user_state["service"] == "appointment":
        if user_state["step"] == "ask_phone":
            user_state["step"] = "ask_date"
            return "تم حفظ رقم الجوال ✅.\nالآن من فضلك حدد اليوم والوقت."
        elif user_state["step"] == "ask_date":
            user_state["step"] = "done"
            return f"تم حجز موعدك في {message} ✅.\nسيتم التواصل معك للتأكيد، شكراً لك 🌹."

    if user_state["service"] == "inquiry":
        if user_state["step"] == "ask_ticket":
            user_state["step"] = "ask_email"
            return "تم حفظ رقم التذكرة ✅.\nالآن من فضلك اكتب بريدك الإلكتروني."
        elif user_state["step"] == "ask_email":
            user_state["step"] = "done"
            return "✅ سيتم التواصل معك خلال ساعتين على بريدك الإلكتروني.\nشكراً لتواصلك معنا 🌹."

    if user_state["step"] == "done":
        return "الخدمة انتهت ✅.\nإذا حاب تبدأ من جديد اكتب أي كلمة."

    return "ممكن تختار من القائمة: رفع شكوى / طلب موعد / استفسار عن نتائج."

with gr.Blocks() as demo:
    gr.Markdown("# 🤖 Chatbot: Appointment Assistant")
    gr.ChatInterface(fn=chatbot_logic)

demo.launch()